In [1]:
import numpy as np
import pandas as pd

In [2]:
calendar = pd.read_csv('data/calendar.csv')
calendar.head()

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,2595,6/4/2022,f,$225.00,$225.00,30,1125
1,2595,6/5/2022,f,$225.00,$225.00,30,1125
2,2595,6/6/2022,f,$225.00,$225.00,30,1125
3,2595,6/7/2022,f,$225.00,$225.00,30,1125
4,2595,6/8/2022,f,$225.00,$225.00,30,1125

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
listings = pd.read_csv('data/listings.csv')
listings.head()

C:\Users\matth\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (67) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2595.0,https://www.airbnb.com/rooms/2595,2.022060e+13,6/4/2022,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/f0813a11-40b2...,2845,https://www.airbnb.com/users/show/2845,Jennifer,9/9/2008,"New York, New York, United States",A New Yorker since (Phone number hidden by Air...,a few days or more,39%,19%,f,https://a0.muscache.com/im/pictures/user/50fc5...,https://a0.muscache.com/im/pictures/user/50fc5...,Midtown,6.0,6.0,"['email', 'phone', 'work_email']",t,t,"New York, United States",Midtown,Manhattan,40.75356,-73.98559,Entire rental unit,Entire home/apt,1,NaN,1 bath,NaN,1.0,"[""Essentials"", ""Bathtub"", ""Extra pillows and b...",$225.00,30,1125,30.0,30.0,1125.0,1125.0,30.0,1125.0,NaN,t,0,3,33,308,6/4/2022,48,0,0,11/21/2009,11/4/2019,4.70,4.72,4.62,4.76,4.79,4.86,4.41,NaN,f,3,3,0,0,0.31
1,5121.0,https://www.airbnb.com/rooms/5121,2.022060e+13,6/4/2022,BlissArtsSpace!,One room available for rent in a 2 bedroom apt...,NaN,https://a0.muscache.com/pictures/2090980c-b68e...,7356,https://www.airbnb.com/users/show/7356,Garon,2/3/2009,"New York, New York, United States","I am an artist(painter, filmmaker) and curato...",within an hour,100%,100%,f,https://a0.muscache.com/im/pictures/user/72a61...,https://a0.muscache.com/im/pictures/user/72a61...,Bedford-Stuyvesant,1.0,1.0,"['email', 'phone']",t,t,NaN,Bedford-Stuyvesant,Brooklyn,40.68535,-73.95512,Private room in rental unit,Private room,2,NaN,NaN,1.0,1.0,"[""Heating"", ""Long term stays allowed"", ""Kitche...",$60.00,30,730,30.0,30.0,730.0,730.0,30.0,730.0,NaN,t,30,60,90,365,6/4/2022,50,0,0,5/28/2009,12/2/2019,4.52,4.22,4.09,4.91,4.91,4.47,4.52,NaN,f,2,0,2,0,0.32
2,5136.0,https://www.airbnb.com/rooms/5136,2.022060e+13,6/4/2022,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,https://www.airbnb.com/users/show/7378,Rebecca,2/3/2009,"Brooklyn, New York, United States","Rebecca is an artist/designer, and Henoch is i...",within an hour,100%,50%,f,https://a0.muscache.com/im/users/7378/profile_...,https://a0.muscache.com/im/users/7378/profile_...,Greenwood Heights,1.0,1.0,"['email', 'phone']",t,t,NaN,Sunset Park,Brooklyn,40.66265,-73.99454,Entire rental unit,Entire home/apt,4,NaN,1.5 baths,2.0,2.0,"[""Dryer"", ""Heating"", ""Hair dryer"", ""Carbon mon...",$275.00,21,1125,21.0,21.0,1125.0,1125.0,21.0,1125.0,NaN,t,3,3,4,250,6/4/2022,2,1,0,1/2/2014,8/8/2021,5.00,5.00,5.00,5.00,5.00,4.50,5.00,NaN,f,1,1,0,0,0.02
3,5178.0,https://www.airbnb.com/rooms/5178,2.022060e+13,6/4/2022,Large Furnished Room Near B'way,Please don’t expect the luxury here just a bas...,"Theater district, many restaurants around here.",https://a0.muscache.com/pictures/12065/f070997...,8967,https://www.airbnb.com/users/show/8967,Shunichi,3/3/2009,"New York, New York, United States",I used to work for a financial industry but no...,within a day,100%,100%,f,https://a0.muscache.com/im/users/8967/profile_...,https://a0.muscache.com/im/users/8967/profile_...,Hell's Kitchen,1.0,1.0,"['email', 'phone']",t,f,"New York, United States",Midtown,Manhattan,40.76457,-73.98317,Private room in rental unit,Private room,2,NaN,1 bath,1.0,1.0,"[""Conditioner"", ""Essentials"", ""Extra pillows a...",$68.00,2,14,2.0,2.0,14.0,14.0,2.0,14.0,NaN,t,3,5,9,172,6/4/2022,536,62,2,5/6/2009,5/9/2022,4.23,4.24,3.75,4.66,4.44,4.87,4.39,NaN,f,1,0,1,0,3.37
4,5203.0,https://www.airbnb.com/rooms/5203,2.022060e+13,6/3/2022,Cozy Clean Guest Room - Family Apt,"Our best guests are seeking a safe, clean, spa...",Our neighborhood is full of restaurants and ca...,https://a0.muscache.com/pictures/103776/b37157...,7490,https://www.airbnb.com/users/show/7490,MaryEllen,2/5/2009,"New York, New York, United States",Welcome to family life with my oldest two away...,NaN,NaN,NaN,f,https://a0.muscache.com/im/users/7490/profile_...,https://a0.muscache.com/im/users/7490/profile_...,Upper West Side,1.0,1.0,"['email', 'phone']",t,t,"New York, United States",Upper West Side,Manhattan,40.80380,-73.96751,Private room in rental unit,Private room,1,NaN,1 shared bath,1.0,1.0,"[""Carbon monoxide alarm"", ""Heating"", ""Essentia...",$75.00,2,14,2.0,2.0,14.0,14.0,2.0,14.0,NaN,t,0,0,0,0,6/3/2022,118,0,0,9/7/2009,7/21/2017,4.91,4.83,4.82,4.97,4.95,4.94,4.92,NaN,f,1,0,1,0,0.76

In [5]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 7 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   listing_id      1048575 non-null  int64
 1   date            1048575 non-null  object
 2   available       1048575 non-null  object
 3   price           1048575 non-null  object
 4   adjusted_price  1048575 non-null  object
 5   minimum_nights  1048575 non-null  int64
 6   maximum_nights  1048575 non-null  int64
dtypes: int64(3), object(4)
memory usage: 56.0+ MB

In [6]:
calendar.isnull().sum()

listing_id        0
date              0
available         0
price             0
adjusted_price    0
minimum_nights    0
maximum_nights    0
dtype: int64

In [7]:
calendar['date'] = pd.to_datetime(calendar['date'], format='%m/%d/%Y')

In [8]:
calendar['available'].value_counts()

f    732055
t    316520
Name: available, dtype: int64

In [9]:
#1 for "true" and 0 for "false"
calendar['available'] = calendar['available'].map(lambda x: 1 if x == 't' else 0)
calendar['available'].value_counts()

0    732055
1    316520
Name: available, dtype: int64

In [10]:
calendar['price'] = calendar['price'].map(lambda x: x.replace(',',''))
calendar['price'] = calendar['price'].map(lambda x: float(x[1:]) if x[0] == '$' else float(x))

Price and adjusted_price are the same so we will drop adjusted_price

In [11]:
calendar = calendar.drop(columns=['adjusted_price'])

In [12]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 6 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   listing_id      1048575 non-null  int64
 1   date            1048575 non-null  datetime64[ns]
 2   available       1048575 non-null  int64
 3   price           1048575 non-null  float64
 4   minimum_nights  1048575 non-null  int64
 5   maximum_nights  1048575 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(4)
memory usage: 48.0 MB

In [13]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37410 entries, 0 to 37409
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            37410 non-null  float64
 1   listing_url                                   37410 non-null  object
 2   scrape_id                                     37410 non-null  float64
 3   last_scraped                                  37410 non-null  object
 4   name                                          37396 non-null  object
 5   description                                   36523 non-null  object
 6   neighborhood_overview                         22430 non-null  object
 7   picture_url                                   37410 non-null  object
 8   host_id                                       37410 non-null  int64
 9   host_url                                      37410 non-null  object
 10  host_name                                     37344 non-null  object
 11  host_since                                    37344 non-null  object
 12  host_location                                 37247 non-null  object
 13  host_about                                    21054 non-null  object
 14  host_response_time                            24200 non-null  object
 15  host_response_rate                            24200 non-null  object
 16  host_acceptance_rate                          25678 non-null  object
 17  host_is_superhost                             37344 non-null  object
 18  host_thumbnail_url                            37344 non-null  object
 19  host_picture_url                              37344 non-null  object
 20  host_neighbourhood                            29868 non-null  object
 21  host_listings_count                           37344 non-null  float64
 22  host_total_listings_count                     37344 non-null  float64
 23  host_verifications                            37410 non-null  object
 24  host_has_profile_pic                          37344 non-null  object
 25  host_identity_verified                        37344 non-null  object
 26  neighbourhood                                 22431 non-null  object
 27  neighbourhood_cleansed                        37410 non-null  object
 28  neighbourhood_group_cleansed                  37410 non-null  object
 29  latitude                                      37410 non-null  float64
 30  longitude                                     37410 non-null  float64
 31  property_type                                 37410 non-null  object
 32  room_type                                     37410 non-null  object
 33  accommodates                                  37410 non-null  int64
 34  bathrooms                                     0 non-null      float64
 35  bathrooms_text                                37329 non-null  object
 36  bedrooms                                      33756 non-null  float64
 37  beds                                          36509 non-null  float64
 38  amenities                                     37410 non-null  object
 39  price                                         37410 non-null  object
 40  minimum_nights                                37410 non-null  int64
 41  maximum_nights                                37410 non-null  int64
 42  minimum_minimum_nights                        37395 non-null  float64
 43  maximum_minimum_nights                        37395 non-null  float64
 44  minimum_maximum_nights                        37395 non-null  float64
 45  maximum_maximum_nights                        37395 non-null  float64
 46  minimum_nights_avg_ntm                        37395 non-null  float64
 47  maximum_nights_avg_ntm                        37395 non-null  float64
 48  calendar_updated                              0 non-null      float64
 49  has_availability                              37410 non-null  object
 50  availability_30                               37410 non-null  int64
 51  availability_60                               37410 non-null  int64
 52  availability_90                               37410 non-null  int64
 53  availability_365                              37410 non-null  int64
 54  calendar_last_scraped                         37410 non-null  object
 55  number_of_reviews                             37410 non-null  int64
 56  number_of_reviews_ltm                         37410 non-null  int64
 57  number_of_reviews_l30d                        37410 non-null  int64
 58  first_review                                  29461 non-null  object
 59  last_review                                   29461 non-null  object
 60  review_scores_rating                          29461 non-null  float64
 61  review_scores_accuracy                        28982 non-null  float64
 62  review_scores_cleanliness                     28992 non-null  float64
 63  review_scores_checkin                         28978 non-null  float64
 64  review_scores_communication                   28987 non-null  float64
 65  review_scores_location                        28975 non-null  float64
 66  review_scores_value                           28975 non-null  float64
 67  license                                       4 non-null      object
 68  instant_bookable                              37410 non-null  object
 69  calculated_host_listings_count                37410 non-null  int64
 70  calculated_host_listings_count_entire_homes   37410 non-null  int64
 71  calculated_host_listings_count_private_rooms  37410 non-null  int64
 72  calculated_host_listings_count_shared_rooms   37410 non-null  int64
 73  reviews_per_month                             29461 non-null  float64
dtypes: float64(24), int64(15), object(35)
memory usage: 21.1+ MB

In [14]:
pd.set_option('display.max_rows', None)

In [15]:
listings.isnull().sum()

id                                                  0
listing_url                                         0
scrape_id                                           0
last_scraped                                        0
name                                               14
description                                       887
neighborhood_overview                           14980
picture_url                                         0
host_id                                             0
host_url                                            0
host_name                                          66
host_since                                         66
host_location                                     163
host_about                                      16356
host_response_time                              13210
host_response_rate                              13210
host_acceptance_rate                            11732
host_is_superhost                                  66
host_thumbnail_url                                 66
host_picture_url                                   66
host_neighbourhood                               7542
host_listings_count                                66
host_total_listings_count                          66
host_verifications                                  0
host_has_profile_pic                               66
host_identity_verified                             66
neighbourhood                                   14979
neighbourhood_cleansed                              0
neighbourhood_group_cleansed                        0
latitude                                            0
longitude                                           0
property_type                                       0
room_type                                           0
accommodates                                        0
bathrooms                                       37410
bathrooms_text                                     81
bedrooms                                         3654
beds                                              901
amenities                                           0
price                                               0
minimum_nights                                      0
maximum_nights                                      0
minimum_minimum_nights                             15
maximum_minimum_nights                             15
minimum_maximum_nights                             15
maximum_maximum_nights                             15
minimum_nights_avg_ntm                             15
maximum_nights_avg_ntm                             15
calendar_updated                                37410
has_availability                                    0
availability_30                                     0
availability_60                                     0
availability_90                                     0
availability_365                                    0
calendar_last_scraped                               0
number_of_reviews                                   0
number_of_reviews_ltm                               0
number_of_reviews_l30d                              0
first_review                                     7949
last_review                                      7949
review_scores_rating                             7949
review_scores_accuracy                           8428
review_scores_cleanliness                        8418
review_scores_checkin                            8432
review_scores_communication                      8423
review_scores_location                           8435
review_scores_value                              8435
license                                         37406
instant_bookable                                    0
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
reviews_per_month                                7949
dtype: int64

In [17]:
listings.shape

(37410, 74)

We have to figure out which columns we need and which we don't

For starters, we don't need listing_url, scrape_id, last_scraped, name, picture_url, host_name, host_since, host_thumbnail_url, host_picture_url, or calendar_last_scraped

In [18]:
listings = listings.drop(columns=['listing_url', 'scrape_id', 'last_scraped', 'name', 'listing_url', 'scrape_id', 'last_scraped',
                                  'name', 'picture_url', 'host_url', 'host_name', 'host_since', 'host_thumbnail_url', 'host_picture_url',
                                  'calendar_last_scraped'])

Same with host location, since it is all in New York

In [19]:
listings = listings.drop(columns=['host_location'])

We will remove any word columns because we don't need them

In [24]:
listings = listings.drop(columns=['description', 'neighborhood_overview', 'host_about'])

In [25]:
listings['host_response_time'].value_counts()

within an hour        14578
within a few hours     5516
within a day           3325
a few days or more      781
Name: host_response_time, dtype: int64

In [26]:
listings['host_response_time'] = listings['host_response_time'].fillna('unknown')

In [27]:
listings['host_response_time'].value_counts()

within an hour        14578
unknown               13210
within a few hours     5516
within a day           3325
a few days or more      781
Name: host_response_time, dtype: int64

Let's drop host_response_rate and host_acceptance_rate since there are too many of them

In [28]:
listings = listings.drop(columns=['host_response_rate', 'host_acceptance_rate'])

host_neighbourhood and neighbourhood is the same so let's drop neighbourhood

In [29]:
listings = listings.drop(columns=['neighbourhood'])

Bathrooms has too many nan values.

In [30]:
listings = listings.drop(columns=['bathrooms', 'bathrooms_text'])

Bedrooms and beds are basically the same same so let's drop bedrooms

In [32]:
listings = listings.drop(columns=['bedrooms'])

Let's fix price

In [33]:
listings['price'] = listings['price'].map(lambda x: x.replace(',',''))
listings['price'] = listings['price'].map(lambda x: float(x[1:]) if x[0] == '$' else float(x))
type(listings['price'])

pandas.core.series.Series

calendar_updated has too many nan values

In [34]:
listings = listings.drop(columns=['calendar_updated'])

Let's combine first_review and last_review

In [35]:
listings['review'] = str(listings['first_review']) + " " + str(listings['last_review'])
listings = listings.drop(columns=['first_review', 'last_review'])

We will drop license then check the nulls again

In [37]:
listings = listings.drop(columns=['license'])

In [38]:
listings.isna().sum()

id                                                 0
host_id                                            0
host_response_time                                 0
host_is_superhost                                 66
host_neighbourhood                              7542
host_listings_count                               66
host_total_listings_count                         66
host_verifications                                 0
host_has_profile_pic                              66
host_identity_verified                            66
neighbourhood_cleansed                             0
neighbourhood_group_cleansed                       0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
beds                                             901
amenities                                          0
price                                              0
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                            15
maximum_minimum_nights                            15
minimum_maximum_nights                            15
maximum_maximum_nights                            15
minimum_nights_avg_ntm                            15
maximum_nights_avg_ntm                            15
has_availability                                   0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
review_scores_rating                            7949
review_scores_accuracy                          8428
review_scores_cleanliness                       8418
review_scores_checkin                           8432
review_scores_communication                     8423
review_scores_location                          8435
review_scores_value                             8435
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               7949
review                                             0
dtype: int64

I am going to readjust the columns so they don't have na values.

In [39]:
listings['review_scores_rating'] = listings['review_scores_rating'].fillna('unknown')
listings['review_scores_accuracy'] = listings['review_scores_accuracy'].fillna('unknown')
listings['review_scores_cleanliness'] = listings['review_scores_cleanliness'].fillna('unknown')
listings['review_scores_checkin'] = listings['review_scores_checkin'].fillna('unknown')
listings['review_scores_communication'] = listings['review_scores_communication'].fillna('unknown')
listings['review_scores_location'] = listings['review_scores_location'].fillna('unknown')
listings['review_scores_value'] = listings['review_scores_value'].fillna('unknown')
listings = listings.drop(columns=['host_neighbourhood', 'reviews_per_month'])
listings.isna().sum()

id                                                0
host_id                                           0
host_response_time                                0
host_is_superhost                                66
host_listings_count                              66
host_total_listings_count                        66
host_verifications                                0
host_has_profile_pic                             66
host_identity_verified                           66
neighbourhood_cleansed                            0
neighbourhood_group_cleansed                      0
latitude                                          0
longitude                                         0
property_type                                     0
room_type                                         0
accommodates                                      0
beds                                            901
amenities                                         0
price                                             0
minimum_nights                                    0
maximum_nights                                    0
minimum_minimum_nights                           15
maximum_minimum_nights                           15
minimum_maximum_nights                           15
maximum_maximum_nights                           15
minimum_nights_avg_ntm                           15
maximum_nights_avg_ntm                           15
has_availability                                  0
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
review_scores_rating                              0
review_scores_accuracy                            0
review_scores_cleanliness                         0
review_scores_checkin                             0
review_scores_communication                       0
review_scores_location                            0
review_scores_value                               0
instant_bookable                                  0
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
calculated_host_listings_count_private_rooms      0
calculated_host_listings_count_shared_rooms       0
review                                            0
dtype: int64

host_total_listings_counts look like basically the same thing as host_listings_counts so let's just drop it

In [40]:
listings = listings.drop(columns=['host_total_listings_count'])

Too many night values listed. Let's just keep the first 2

In [41]:
listings = listings.drop(columns=['minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights',
                                  'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm'])

availability_365 incompasses the rest of them, so let's drop the rest

In [42]:
listings = listings.drop(columns=['availability_30', 'availability_60', 'availability_90'])

Number of reviews and calculated host listings seem to be listed multiple times under different names. Let's change that

In [43]:
listings = listings.drop(columns=['number_of_reviews_ltm', 'number_of_reviews_l30d', 'calculated_host_listings_count_entire_homes',
                                  'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms'])

lets drop na

In [44]:
listings.dropna(inplace=True)
listings.isna().sum()

id                                0
host_id                           0
host_response_time                0
host_is_superhost                 0
host_listings_count               0
host_verifications                0
host_has_profile_pic              0
host_identity_verified            0
neighbourhood_cleansed            0
neighbourhood_group_cleansed      0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
beds                              0
amenities                         0
price                             0
minimum_nights                    0
maximum_nights                    0
has_availability                  0
availability_365                  0
number_of_reviews                 0
review_scores_rating              0
review_scores_accuracy            0
review_scores_cleanliness         0
review_scores_checkin             0
review_scores_communication       0
review_scores_location            0
review_scores_value               0
instant_bookable                  0
calculated_host_listings_count    0
review                            0
dtype: int64

In [45]:
listings.head()

,id,host_id,host_response_time,host_is_superhost,host_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,beds,amenities,price,minimum_nights,maximum_nights,has_availability,availability_365,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,review
0,2595.0,2845,a few days or more,f,6.0,"['email', 'phone', 'work_email']",t,t,Midtown,Manhattan,40.75356,-73.98559,Entire rental unit,Entire home/apt,1,1.0,"[""Essentials"", ""Bathtub"", ""Extra pillows and b...",225.0,30,1125,t,308,48,4.7,4.72,4.62,4.76,4.79,4.86,4.41,f,3,0 11/21/2009\n1 5/28/2009\n2 ...
1,5121.0,7356,within an hour,f,1.0,"['email', 'phone']",t,t,Bedford-Stuyvesant,Brooklyn,40.68535,-73.95512,Private room in rental unit,Private room,2,1.0,"[""Heating"", ""Long term stays allowed"", ""Kitche...",60.0,30,730,t,365,50,4.52,4.22,4.09,4.91,4.91,4.47,4.52,f,2,0 11/21/2009\n1 5/28/2009\n2 ...
2,5136.0,7378,within an hour,f,1.0,"['email', 'phone']",t,t,Sunset Park,Brooklyn,40.66265,-73.99454,Entire rental unit,Entire home/apt,4,2.0,"[""Dryer"", ""Heating"", ""Hair dryer"", ""Carbon mon...",275.0,21,1125,t,250,2,5.0,5.0,5.0,5.0,5.0,4.5,5.0,f,1,0 11/21/2009\n1 5/28/2009\n2 ...
3,5178.0,8967,within a day,f,1.0,"['email', 'phone']",t,f,Midtown,Manhattan,40.76457,-73.98317,Private room in rental unit,Private room,2,1.0,"[""Conditioner"", ""Essentials"", ""Extra pillows a...",68.0,2,14,t,172,536,4.23,4.24,3.75,4.66,4.44,4.87,4.39,f,1,0 11/21/2009\n1 5/28/2009\n2 ...
4,5203.0,7490,unknown,f,1.0,"['email', 'phone']",t,t,Upper West Side,Manhattan,40.80380,-73.96751,Private room in rental unit,Private room,1,1.0,"[""Carbon monoxide alarm"", ""Heating"", ""Essentia...",75.0,2,14,t,0,118,4.91,4.83,4.82,4.97,4.95,4.94,4.92,f,1,0 11/21/2009\n1 5/28/2009\n2 ...

Let's turn all t f columns into 1 and 0 columns where 1 is t and 0 is f

In [46]:
listings['host_is_superhost'] = listings['host_is_superhost'].map(lambda x: 1 if x == 't' else 0)
listings['host_has_profile_pic'] = listings['host_has_profile_pic'].map(lambda x: 1 if x == 't' else 0)
listings['host_identity_verified'] = listings['host_identity_verified'].map(lambda x: 1 if x == 't' else 0)
listings['has_availability'] = listings['has_availability'].map(lambda x: 1 if x == 't' else 0)
listings['instant_bookable'] = listings['instant_bookable'].map(lambda x: 1 if x == 't' else 0)

In [47]:
listings.shape

(36454, 33)

In [48]:
len(calendar['listing_id'].unique())

2873

In [49]:
listings['id'] = listings['id'].map(lambda x: int(x))
len(listings['id'].unique())

36303

Let's merge calendar and listings

In [50]:
calendar = calendar.rename(columns={'listing_id': 'id'})
calendar.head()

     id       date  available  price  minimum_nights  maximum_nights
0  2595 2022-06-04          0  225.0              30            1125
1  2595 2022-06-05          0  225.0              30            1125
2  2595 2022-06-06          0  225.0              30            1125
3  2595 2022-06-07          0  225.0              30            1125
4  2595 2022-06-08          0  225.0              30            1125

In [51]:
df_full = pd.merge(calendar, listings.drop(columns=['price', 'minimum_nights', 'maximum_nights']), how='left', on='id')
df_full.head()

,id,date,available,price,minimum_nights,maximum_nights,host_id,host_response_time,host_is_superhost,host_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,beds,amenities,has_availability,availability_365,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,review
0,2595,2022-06-04,0,225.0,30,1125,2845.0,a few days or more,0.0,6.0,"['email', 'phone', 'work_email']",1.0,1.0,Midtown,Manhattan,40.75356,-73.98559,Entire rental unit,Entire home/apt,1.0,1.0,"[""Essentials"", ""Bathtub"", ""Extra pillows and b...",1.0,308.0,48.0,4.7,4.72,4.62,4.76,4.79,4.86,4.41,0.0,3.0,0 11/21/2009\n1 5/28/2009\n2 ...
1,2595,2022-06-05,0,225.0,30,1125,2845.0,a few days or more,0.0,6.0,"['email', 'phone', 'work_email']",1.0,1.0,Midtown,Manhattan,40.75356,-73.98559,Entire rental unit,Entire home/apt,1.0,1.0,"[""Essentials"", ""Bathtub"", ""Extra pillows and b...",1.0,308.0,48.0,4.7,4.72,4.62,4.76,4.79,4.86,4.41,0.0,3.0,0 11/21/2009\n1 5/28/2009\n2 ...
2,2595,2022-06-06,0,225.0,30,1125,2845.0,a few days or more,0.0,6.0,"['email', 'phone', 'work_email']",1.0,1.0,Midtown,Manhattan,40.75356,-73.98559,Entire rental unit,Entire home/apt,1.0,1.0,"[""Essentials"", ""Bathtub"", ""Extra pillows and b...",1.0,308.0,48.0,4.7,4.72,4.62,4.76,4.79,4.86,4.41,0.0,3.0,0 11/21/2009\n1 5/28/2009\n2 ...
3,2595,2022-06-07,0,225.0,30,1125,2845.0,a few days or more,0.0,6.0,"['email', 'phone', 'work_email']",1.0,1.0,Midtown,Manhattan,40.75356,-73.98559,Entire rental unit,Entire home/apt,1.0,1.0,"[""Essentials"", ""Bathtub"", ""Extra pillows and b...",1.0,308.0,48.0,4.7,4.72,4.62,4.76,4.79,4.86,4.41,0.0,3.0,0 11/21/2009\n1 5/28/2009\n2 ...
4,2595,2022-06-08,0,225.0,30,1125,2845.0,a few days or more,0.0,6.0,"['email', 'phone', 'work_email']",1.0,1.0,Midtown,Manhattan,40.75356,-73.98559,Entire rental unit,Entire home/apt,1.0,1.0,"[""Essentials"", ""Bathtub"", ""Extra pillows and b...",1.0,308.0,48.0,4.7,4.72,4.62,4.76,4.79,4.86,4.41,0.0,3.0,0 11/21/2009\n1 5/28/2009\n2 ...

In [52]:
df_full.shape

(1048575, 35)

In [53]:
df_full.isna().sum()

id                                    0
date                                  0
available                             0
price                                 0
minimum_nights                        0
maximum_nights                        0
host_id                           12410
host_response_time                12410
host_is_superhost                 12410
host_listings_count               12410
host_verifications                12410
host_has_profile_pic              12410
host_identity_verified            12410
neighbourhood_cleansed            12410
neighbourhood_group_cleansed      12410
latitude                          12410
longitude                         12410
property_type                     12410
room_type                         12410
accommodates                      12410
beds                              12410
amenities                         12410
has_availability                  12410
availability_365                  12410
number_of_reviews                 12410
review_scores_rating              12410
review_scores_accuracy            12410
review_scores_cleanliness         12410
review_scores_checkin             12410
review_scores_communication       12410
review_scores_location            12410
review_scores_value               12410
instant_bookable                  12410
calculated_host_listings_count    12410
review                            12410
dtype: int64

In [54]:
df_full = df_full.dropna()
df_full.shape

(1036165, 35)

In [55]:
df_full['month'] = df_full['date'].dt.month
month_dict = {1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'May', 6: 'Jun', 7: 'Jul', 8: 'Aug', 9: 'Sep', 10: 'Oct', 11: 'Nov', 12: 'Dec'}
df_full['month'] = df_full['month'].map(lambda x: month_dict[x])
df_full['month'].value_counts()

Jul    88009
Aug    88009
Oct    88009
Dec    88009
Jan    88009
Mar    88002
May    87978
Sep    85170
Nov    85170
Jun    85168
Apr    85140
Feb    79492
Name: month, dtype: int64

Now let's export this data set

In [57]:
df_full.to_hdf(r'data/df_full.h5', key='stage', mode='w')